# This workflow will build and test an iOS project using Xcode

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14  # Ensure compatibility with GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Installed Xcode Versions
      run: ls /Applications | grep Xcode

    - name: Set Up Xcode 16.2
      run: |
        if [ -d "/Applications/Xcode_16.2.app" ]; then
          sudo xcode-select -s /Applications/Xcode_16.2.app
        else
          echo "⚠️ Xcode 16.2 not found, using default version."
        fi

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: List Available iOS Simulators (Before Installation)
      run: xcrun simctl list devices

    - name: Install iOS 17.0 Simulator (If Not Installed)
      run: |
        if ! xcrun simctl list devices | grep -q "iOS 17.0"; then
          echo "Installing iOS 17.0 Simulator..."
          sudo xcodebuild -downloadPlatform iOS -version 17.0 || echo "Skipping installation if already present"
        else
          echo "✅ iOS 17.0 Simulator already installed."
        fi

    - name: Boot iPhone 15 Pro Simulator (iOS 17.0)
      run: |
        if xcrun simctl list devices | grep -q "iPhone 15 Pro (.*) (Shutdown)"; then
          xcrun simctl boot "iPhone 15 Pro" || echo "Skipping boot if already running"
        else
          echo "⚠️ iPhone 15 Pro (iOS 17.0) not found, using any available iOS Simulator"
        fi

    - name: Clean & Build Project
      run: xcodebuild clean build -scheme swift_counter -sdk iphonesimulator -destination "generic/platform=iOS Simulator" | xcpretty

    - name: Run Unit Tests
      run: xcodebuild test -scheme swift_counter -sdk iphonesimulator -destination "generic/platform=iOS Simulator" | xcpretty