# This workflow will build and test an iOS project using Xcode

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Xcode 16.2
      run: |
        if [ -d "/Applications/Xcode_16.2.app" ]; then
          sudo xcode-select -s /Applications/Xcode_16.2.app
        else
          echo "⚠️ Xcode 16.2 not found, using default version."
        fi

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: List Available iOS Simulators
      run: xcrun simctl list devices

    - name: Select an Available iOS 17.0 Simulator
      id: select_simulator
      run: |
        SIMULATOR_ID=$(xcrun simctl list devices available | grep -Eo '[0-9A-F\-]+.*(iOS 17.0)' | head -n 1 | awk '{print $1}')
        if [[ -z "$SIMULATOR_ID" ]]; then
          echo "❌ No available iOS 17.0 simulator found. Exiting..."
          exit 1
        fi
        echo "✅ Using simulator: $SIMULATOR_ID"
        echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

    - name: Boot Selected iOS Simulator
      run: xcrun simctl boot "$SIMULATOR_ID"

    - name: Clean & Build Project
      run: xcodebuild clean build -scheme swift_counter -sdk iphonesimulator -destination "id=$SIMULATOR_ID" | xcpretty

    - name: Run Unit Tests
      run: xcodebuild test -scheme swift_counter -sdk iphonesimulator -destination "id=$SIMULATOR_ID" | xcpretty