# This workflow will build and test an iOS project using Xcode
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_12.5.app
    - name: Build
      run: xcodebuild -scheme swift_counter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' build
    - name: Run tests
      run: xcodebuild test -scheme swift_counter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'
