# This workflow will build and test an iOS project using Xcode

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Xcode 16.2
      run: |
        if [ -d "/Applications/Xcode_16.2.app" ]; then
          sudo xcode-select -s /Applications/Xcode_16.2.app
        else
          echo "⚠️ Xcode 16.2 not found, using default version."
        fi

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: List Available iOS Simulators
      run: xcrun simctl list devices

    - name: Select an Available iOS 17.0 Simulator
      id: select_simulator
      run: |
        # Use awk to find the section for iOS 17.0 and then look for a line with "iPhone 15 Pro"
        SIMULATOR_ID=$(xcrun simctl list devices | \
          awk '/-- iOS 17.0 --/{flag=1; next} /^--/{flag=0} flag && /iPhone 15 Pro/ { match($0, /\(([0-9A-F\-]+)\)/, arr); print arr[1]; exit }')
        if [[ -z "$SIMULATOR_ID" ]]; then
          echo "❌ No available iOS 17.0 iPhone 15 Pro simulator found. Exiting..."
          exit 1
        fi
        echo "✅ Using simulator with UDID: $SIMULATOR_ID"
        echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

    - name: Boot Selected iOS Simulator
      run: |
        echo "Booting simulator with UDID: $SIMULATOR_ID"
        xcrun simctl boot "$SIMULATOR_ID"
        # Wait until the simulator is fully booted
        xcrun simctl bootstatus "$SIMULATOR_ID" -b

    - name: Clean & Build Project
      run: |
        xcodebuild clean build \
          -scheme swift_counter \
          -sdk iphonesimulator \
          -destination "id=$SIMULATOR_ID" | xcpretty

    - name: Run Unit Tests
      run: |
        xcodebuild test \
          -scheme swift_counter \
          -sdk iphonesimulator \
          -destination "id=$SIMULATOR_ID" | xcpretty