# This workflow will build and test an iOS project using Xcode

name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Installed Xcode Versions
      run: ls /Applications | grep Xcode

    - name: Set Up Xcode 16.2
      run: |
        if [ -d "/Applications/Xcode_16.2.app" ]; then
          sudo xcode-select -s /Applications/Xcode_16.2.app
        else
          echo "⚠️ Xcode 16.2 not found, using default version."
        fi

    - name: Verify Xcode Version
      run: xcodebuild -version

    - name: List Available iOS Simulators
      run: xcrun simctl list devices

    - name: Boot iPhone 15 Pro Simulator (iOS 17.0)
      run: xcrun simctl boot "iPhone 15 Pro"

    - name: Clean & Build Project
      run: xcodebuild clean build -scheme swift_counter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' | xcpretty

    - name: Run Unit Tests
      run: xcodebuild test -scheme swift_counter -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' | xcpretty